### PR TITLE
CI pipeline

### PR DESCRIPTION
**Pull request by melezhik**
Current build fails now - https://ci.sparrowhub.io/report/2288 

HTH

Aleksei

### CODE REVIEW

**Comment by grondilu** [comment]
`kdf` command was added to openssl 3.0 (https://www.openssl.org/news/cl30.txt), so I assume this test suite is using an older version.

I'll see if I can test the openssl version and skip relevant tests if need be.

**Comment by melezhik** [comment]
👍

**Comment by melezhik** [comment]
Yeah , you need to add this repo to your repos list in your SparrowCI account  to start new builds. Thanks !

**Comment by melezhik** [comment]
looks like latest commits has made the whole build run much longer - my SparrowCI workers timeouted - https://sparky.sparrowhub.io/report/multi-versions/10812

**Comment by grondilu** [comment]
> looks like latest commits has made the whole build run much longer - my SparrowCI workers timeouted - https://sparky.sparrowhub.io/report/multi-versions/10812

Apparently the test runs the part I thought I was skipping when not using openssl.  Not sure what I missed.  I'll look into it.

**Comment by melezhik** [comment]
sorry this comment was meant to bitcoin-raku-tools, and this is actually not a timeout but out of memory error, so docker instance running a test gets kicked of by kernel ...

**Comment by melezhik** [comment]
> Apparently the test runs the part I thought I was skipping when not using openssl. Not sure what I missed. I'll look into it.

do you mean all these `[Bitcoin] PBKDF2` tests, right?

**Comment by grondilu** [comment]
> > Apparently the test runs the part I thought I was skipping when not using openssl. Not sure what I missed. I'll look into it.
> 
> do you mean all these `[Bitcoin] PBKDF2` tests, right?

Yes.  They are progress indicators :

https://github.com/grondilu/bitcoin-raku-tools/blob/655ef77e239c55b9a5cf7bb643ea5322f1847705/lib/BIP39.rakumod#L28

**Comment by melezhik** [comment]
well, now the last pipeline just fails - https://ci.sparrowhub.io/report/2288 with the old `Invalid command 'kdf';` error

**Comment by melezhik** [comment]
there is raku-sparrow channel on irc where we can also discuss things ...

**Comment by grondilu** [comment]
> well, now the last pipeline just fails - https://ci.sparrowhub.io/report/2288 with the old `Invalid command 'kdf';` error

this makes sense as this run was for the 0.6.0 version, which I'm pretty sure was before I added the openssl version test.

**Pull request merged**
